dwmc and gaps fix

diff --git a/dwmc b/dwmc
--- a/dwmc
+++ b/dwmc
@@ -1,40 +1,80 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 signal() {
 	xsetroot -name "fsignal:$*"
 }
 
 case $# in
-1)
-	case $1 in
-	setlayout | view | viewall | togglebar | togglefloating | zoom | killclient | quit)
-		signal $1
+	1)
+		case $1 in
+			defaultgaps) ;&
+			killclient) ;&
+			quit) ;&
+			setlayout) ;&
+			setcfact) ;&
+			togglebar) ;&
+			togglefloating) ;&
+			togglegaps) ;&
+			togglesticky) ;&
+			view) ;&
+			viewall) ;&
+			zoom)
+				signal $1
+				;;
+			*)
+				echo "Unknown command ($1) or missing one argument."
+				exit 1
+			;;
+		esac
 		;;
-	*)
-		echo "Unknown command or missing one argument."
-		exit 1
+	2)
+		case $1 in
+			togglescratch) ;&
+			view)
+				signal $1 ui $2
+				;;
+			incnmaster) ;&
+			incrgaps) ;&
+			focusmon) ;&
+			focusstack) ;&
+			pushstack) ;&
+			setlayoutex) ;&
+			setgaps) ;&
+			tagex) ;&
+			tagmon) ;&
+			toggletagex) ;&
+			toggleviewex) ;&
+			viewex)
+				signal $1 i $2
+				;;
+			setcfact) ;&
+			setmfact)
+				signal $1 f $2
+				;;
+			*)
+				echo "Unknown command ($1) or too many arguments"
+				exit 1
+				;;
+		esac
 		;;
-	esac
-	;;
-2)
-	case $1 in
-	view)
-		signal $1 ui $2
-		;;
-	viewex | toggleviewex | tagex | toggletagex | setlayoutex | focusstack | incnmaster | focusmon | tagmon)
-		signal $1 i $2
-		;;
-	setmfact)
-		signal $1 f $2
+	5)
+		case $1 in
+			setgaps)
+				# Expects "setgaps oh ov ih iv" where -1 means to keep existing values
+				[ $2 = -1 ] && oh=128 || oh=$2
+				[ $3 = -1 ] && ov=128 || ov=$3
+				[ $4 = -1 ] && ih=128 || ih=$4
+				[ $5 = -1 ] && iv=128 || iv=$5
+				signal $1 i $(((oh << 24) + (ov << 16) + (ih << 8) + iv))
+				;;
+			*)
+				echo "Unknown command ($1) or too many arguments"
+				exit 1
+				;;
+		esac
 		;;
 	*)
 		echo "Unknown command or one too many arguments."
 		exit 1
 		;;
-	esac
-	;;
-*)
-	echo "Too many arguments."
-	exit 1
-	;;
 esac
